export 'package:multi_login/presentation/admin/addgenuser/admin_addgenuser.screen.dart';
export 'package:multi_login/presentation/admin/addproduct/admin_addproduct.screen.dart';
export 'package:multi_login/presentation/admin/adduser/adduser.screen.dart';
export 'package:multi_login/presentation/admin/addvendor/admin_addvendor.screen.dart';
export 'package:multi_login/presentation/admin/home/home.screen.dart';
export 'package:multi_login/presentation/douser/douser.screen.dart';
export 'package:multi_login/presentation/generaluser/generaluser.screen.dart';
export 'package:multi_login/presentation/login/login.screen.dart';
export 'package:multi_login/presentation/splash/splash.screen.dart';